SELECT *
FROM FINANCIAL_DATA;

/*==================================================
                KPIs
==================================================*/

-----KPI 1 — Total Budget
SELECT SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET
FROM FINANCIAL_DATA;

-----KPI 2 – Total Actual Expense
SELECT SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL_EXPENSE
FROM FINANCIAL_DATA;

-----KPI 3 – Budget Variance
SELECT SUM(BUDGET_AMOUNT) - SUM(ACTUAL_AMOUNT) AS BUDGET_VARIANCE
FROM FINANCIAL_DATA;

-----KPI 4 – Budget Utilization %
SELECT ROUND((SUM(ACTUAL_AMOUNT) / SUM(BUDGET_AMOUNT)) * 100, 2)
       AS BUDGET_UTILIZATION
FROM FINANCIAL_DATA;

----KPI 5 – Average Expense per Transaction
SELECT ROUND(AVG(ACTUAL_AMOUNT), 2) AS AVG_EXPENSE_PER_TRANSACTION
FROM FINANCIAL_DATA;

/*==================================================
                BUSINESS QUESTIONS
==================================================*/

-------1 – Budget vs Actual Performance
SELECT 
    SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
    SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL_EXPENSE,
    SUM(ACTUAL_AMOUNT) - SUM(BUDGET_AMOUNT) AS VARIANCE
FROM FINANCIAL_DATA;

-----2 – Department-wise Budget Performance
SELECT
    DEPARTMENT,
    SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
    SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL_EXPENSE,
    SUM(ACTUAL_AMOUNT) - SUM(BUDGET_AMOUNT) AS VARIANCE
FROM FINANCIAL_DATA
GROUP BY DEPARTMENT
ORDER BY VARIANCE DESC;

------3 – Category-wise Spending Analysis
SELECT
    CATEGORY,
    SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL_EXPENSE
FROM FINANCIAL_DATA
GROUP BY CATEGORY
ORDER BY TOTAL_ACTUAL_EXPENSE DESC;

------4 – Region-wise Spending Analysis
SELECT
    REGION,
    SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL_EXPENSE
FROM FINANCIAL_DATA
GROUP BY REGION
ORDER BY TOTAL_ACTUAL_EXPENSE DESC;

------5 –Monthly Budget vs Actual Expenses
SELECT
    TO_CHAR(TRUNC(TRANSACTION_DATE, 'MM'), 'Mon YYYY') AS MONTH,
    ROUND(SUM(BUDGET_AMOUNT), 2) AS TOTAL_BUDGET,
    ROUND(SUM(ACTUAL_AMOUNT), 2) AS TOTAL_ACTUAL_EXPENSE
FROM FINANCIAL_DATA
GROUP BY TRUNC(TRANSACTION_DATE, 'MM')
ORDER BY TRUNC(TRANSACTION_DATE, 'MM');

SELECT COUNT(*) AS TOTAL_RECORDS
FROM FINANCIAL_DATA;